import{a as L,S,i as d}from"./assets/vendor-eded45c0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function h(s,t){try{const o="https://pixabay.com/api/",a="43587882-3fd012595c4df59010c013d1f",{data:e}=await L.get(o,{params:{key:a,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}});return e}catch(o){throw console.error("Error fetching data, please try again:",o),new Error(o.response.status)}}function y(s){return s.reduce((t,{webformatURL:o,largeImageURL:a,tags:e,likes:r,views:i,comments:b,downloads:_})=>t+=`
        <li class="gallery-item">
            <a class="gallery-link" href="${a}">
                <img class="gallery-img" src="${o}" alt="${e}" />
            </a>
            <div class="gallery-block">
                <p class="gallery-block__description"><span>likes</span>${r}</p>
                <p class="gallery-block__description"><span>views</span>${i}</p>
                <p class="gallery-block__description"><span>comments</span> ${b}</p>
                <p class="gallery-block__description"><span>downloads</span>${_}</p>
            </div>
        </li>
        `,"")}let f=new S(".gallery a",{sourceAttr:"href",captionsData:"alt",captionPosition:"bottom",captionDelay:250});const u=document.querySelector(".js__search-form"),p=document.querySelector(".js__list"),m=document.querySelector(".loader"),n=document.querySelector(".button__load-btn");let l,c=1,g=15;u.addEventListener("submit",w);n.addEventListener("click",v);async function w(s){s.preventDefault(),l=u.elements.picture.value.trim(),p.innerHTML="",m.classList.remove(".hide");try{const t=await h(l,c);if(l){p.insertAdjacentHTML("beforeend",y(t.hits)),f.refresh();const o=Math.ceil(t.totalHits/g);c<o&&n.classList.replace("load-more-hidden","load-more")}else{d.error({title:"Error",message:"Sorry, your request is not correct. Please try again!"});return}}catch{d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",transitionIn:"bounceInUp",messageColor:"white",timeout:2e3})}finally{u.reset()}}async function v(){c+=1,n.disabled=!0,m.classList.remove(".hide");try{const s=await h(l,c),t=Math.ceil(s.totalHits/g);p.insertAdjacentHTML("beforeend",y(s.hits)),n.disabled=!1,f.refresh();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:Math.round(o)*2,behavior:"smooth"}),c>=t&&(n.classList.replace("load-more","load-more-hidden"),d.show({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",transitionIn:"bounceInUp",messageColor:"white",timeout:2e3})}finally{m.classList.add("hide")}}
//# sourceMappingURL=commonHelpers.js.map
